spring:  jpa:    properties:      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect     
        # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: update    #`hibernate_sequence' doesn't exist    hibernate.use-new-id-generator-mappings: false
    show-sql: true    
---
spring.profiles: local
    
spring.datasource:
#  url: jdbc:postgresql://localhost:5432/akuc_db
#  username: postgres
#  password: password  url: jdbc:mysql://localhost:13306/akuc_db  username: akuc_db_user  password: password
  hikari:    connectionTimeout: 20000    maximumPoolSize: 5# App Propertiesjavarako:  jwtSecret: javarakoSecretKey  jwtExpirationMs: 600000