spring:  profiles:    active: prod  jpa:    properties:      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL8Dialect     
        # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: update    #`hibernate_sequence' doesn't exist    hibernate.use-new-id-generator-mappings: false
    show-sql: trueserver:  port : 8081logging:  level:     org.springframework.core: INFO
---
spring.profiles: local
    
spring.datasource:
#  url: jdbc:postgresql://localhost:5432/akuc_db
#  username: postgres
#  password: password#  url: jdbc:mysql://localhost:13306/akuc_db#  username: akuc_db_user#  password: password
  url: jdbc:mysql://database-akuc.czjdtmcrp6lf.us-east-1.rds.amazonaws.com:3306/akuc_db?serverTimezone=America/Toronto&useLegacyDatetimeCode=false  username: akucadmin  password: Makuc6610    hikari:    connectionTimeout: 20000    maximumPoolSize: 10# App Propertiesjavarako:  jwtSecret: javarakoSecretKey  jwtExpirationMs: 3600000  ---spring.profiles: prod    spring.datasource:  url: jdbc:mysql://database-akuc.czjdtmcrp6lf.us-east-1.rds.amazonaws.com:3306/akuc_db?serverTimezone=America/Toronto&useLegacyDatetimeCode=false  username: akucadmin  password: Makuc6610  hikari:    connectionTimeout: 20000    maximumPoolSize: 10# App Propertiesjavarako:  jwtSecret: javarakoSecretKey  jwtExpirationMs: 3600000  