spring:  jpa:    properties:      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect     
        # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: update
    show-sql: true    
---
spring.profiles: local
    
spring.datasource:
  url: jdbc:postgresql://localhost:5432/akuc_db
  username: postgres
  password: password
  hikari:    connectionTimeout: 20000    maximumPoolSize: 5